=== tarun786/GuruDemoSiteAutomation/src/test/java/GuruAutomation/GuruDemoSiteAutomation/example/catalogstype.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/catalogstype"
	xmlns:tns="http://www.example.org/catalogstype" elementFormDefault="qualified">

	<element name="globalcatalogs" type="tns:catalogtype"></element>
	<complexType name="catalogtype">
		<sequence>
			<element name="book" type="tns:booktype" maxOccurs="3"
				minOccurs="1"></element>
		</sequence>

	</complexType>

	<complexType name="booktype">

		<sequence>
			<element name="author" type="string"></element>
			<element name="title" type="tns:myTitle"></element>
			<element name="genre" type="string"></element>
			<element name="price" type="tns:Myprice"></element>
			<element name="publish_date" type="date"></element>
			<element name="description" type="string"></element>
		</sequence>
		<attribute name="id" type="ID" use="required"></attribute>

	</complexType>

	<simpleType name="Myprice">
		<restriction base="double">
			<minInclusive value="5.0"></minInclusive>
			<maxExclusive value="50.5"></maxExclusive>
		</restriction>

	</simpleType>

	<simpleType name="myTitle">
		<restriction base="string">
			<minLength value="5"></minLength>
			<maxLength value="12"></maxLength>
		</restriction>
	</simpleType>

</schema>

=== tarun786/GuruDemoSiteAutomation/src/test/java/GuruAutomation/GuruDemoSiteAutomation/example/Newcatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalcatalogs xmlns:tns="http://www.example.org/catalogstype" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/catalogstype catalogstype.xsd ">
  <tns:book id="A1">
    <tns:author>"Tarun Jaiswal"</tns:author>
    <tns:title>"2 states"</tns:title>
    <tns:genre>"Mix Love"</tns:genre>
    <tns:price>45.5</tns:price>
    <tns:publish_date>2001-01-01</tns:publish_date>
    <tns:description>"This is a one of good novel in the world"</tns:description>
  </tns:book>
  
    <tns:book id="A2">
    <tns:author>"Manoj"</tns:author>
    <tns:title>"3 states"</tns:title>
    <tns:genre>"Mix Love"</tns:genre>
    <tns:price>48.5</tns:price>
    <tns:publish_date>2001-01-01</tns:publish_date>
    <tns:description>"This is a one of good novel in the world"</tns:description>
  </tns:book>
</tns:globalcatalogs>
